### ISSUE TITLE
1.20.1 release?

### ISSUE THREAD

**Issue by b1bradders** [kgriff0n/everything-is-tnt#1]
Would build the mod myself for 1.20.1 but I can't be bothered. I want to use this with Create (which supports up to 1.20.1).

:)

**Comment by kgriff0n** [comment]
This mod cannot be built in 1.20.1, the tnt `block_state` field has been added in 1.20.3, sorry :(

**Comment by b1bradders** [comment]
Yeah I decided in the end that I would build it myself and swiftly ran into that issue. Honestly, I tried for an hour to see if maybe I could make a custom block entity that is basically a clone of TNT but has a modifiable block state but I just couldn't find anything. Maybe I could copy code from 1.20.3 and port it to .1 but I highly doubt that'd work and I'm sure I'd have to change a lot of things.

Thanks though!
